version: 1

services:
  - type: web
    name: backlabs-api
    env: node
    plan: free
    rootDir: backlabs-api
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - fromDatabase:
          name: backlabs-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false

  - type: static
    name: backlabs-front
    env: static
    plan: free
    rootDir: backlabs
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://backlabs-api.onrender.com/api

databases:
  - name: backlabs-db
    type: postgres
    plan: free